---
title: "PS270 Final Project"
author: "Brandon Wagner"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

I am interested in exploring data related to the olympics (because that's topical right now) or something football/basketball related


My research question is the following: How do socioeconomic factors of a country (unemployement, gdp, gdp per capita, education levels, and poverty rate) impact the number of olympic medals won by a country throughout the history of the modern Summer and Winter Olympics (1896-2024)? I hypothesize that countries with "better" socioeconomic indicators (ex. low unemployment, higher gdp per capita, more education) have a higher likelihood of winning medals. I believe this because countries with stronger economies are able to better train their athletes and have more sports competition, leading to more medals being won. I also will compare the percentages of medalists within a country's delegation to see how successful each country is. For each of the socioeconomic indicators, I will take values of each of them from each olympic year and use those values in my analysis. I will use the already created dataset of medals won to gather the list for every olympic year (it is measured by count of each type of medal). A positive correlation between gdp, gdp per capita, and education levels with medals won as well as a negative correlation between unemployment, and poverty rate with medals won would indicate support for my hypothesis as the "better" indicators should increase as medals are won. A relationship opposite or showing no correlation to those stated above would disprove my hypothesis as it would mean that "better" indicators either have an opposite effect or no effect on medals won.
